# It may be tempting to add parens around each individual clause in this expression, but Travis then builds pushes anyway
if: branch = master OR branch =~ ^features/ OR branch =~ ^release/ OR tag IS present
matrix:
  include:
    - os: linux
      env: NODE_VERSION=v8.11.1 TRAVIS_PUBLISH_PACKAGES=true
    - os: linux
      env: NODE_VERSION=v10.7
    - os: osx
      env: NODE_VERSION=v6.10.3
    - os: linux
      env: NODE_VERSION=v11.0.0
language: go
go: 1.11
sudo: true # give us 7.5GB and >2 bursted cores.
git:
  depth: false
before_install:
    - git clone https://github.com/pulumi/scripts ${GOPATH}/src/github.com/pulumi/scripts
    - source ${GOPATH}/src/github.com/pulumi/scripts/ci/prepare-environment.sh
    - source ${PULUMI_SCRIPTS}/ci/keep-failed-tests.sh
install:
    - source ${PULUMI_SCRIPTS}/ci/install-common-toolchain.sh
before_script:
    - ${PULUMI_SCRIPTS}/ci/ensure-dependencies
script:
    - make travis_${TRAVIS_EVENT_TYPE}
after_failure:
    - ${PULUMI_SCRIPTS}/ci/upload-failed-tests
notifications:
    webhooks: https://zlmgkhmhjc.execute-api.us-west-2.amazonaws.com/stage/travis
env:
  global:
  # testing API server
  - secure: "UCdv91IyevVZJhw6MYRdcTF1o5WHfqYCtu+aVibhQS08OZl/R+tfFH2fJRBW+p3g1JPqT1Tlu8s/X66xz483WQp6RdCELMAW82ca/AWAqE9n7ziZ1eYIKQhECmRnxxN3Lpo52QjpVuDggy+cZIYciBK5ct3zdf4VLdel3LghTrapLlfBqZsFXfUUuZCZKVb1Xz6X2124hlCW6x6Q3IZGKSpK7iw13Wuzr1zEdaADY139o35eVawP+ZeO7WjRJJ6seDxgJWMU+sZ/i7qPvVtUIBxFE/aVxIZZWBdhjKqI42AlMLt5+QZ+oKLMDsKtxqh9kJG+/6OMksUiRuNnp1fRQj+ppty9VHanLG+0NWHNpMr6Lh194RP1lXnU9rIncDRIMzQjH0bolnIHJVchGQhuk0+YAsiqEGRgO5GW+ayncj4fohySILnnVSc69YnYvhQoXqsLl317S1T7VpnxjrVNyAjSrpVI61se894xvpSgWfsSQ2ZnOrnJXmMGGfs7P46+IjOIne6wGyJqd9K1iPUDD/tZTdS2/fKE1OVWG+HmPssVqLhF0yeMRek2INbnSWEqtDfn3uyQ/hD3Ue3vlR0kLmBVxq9Py5CTb0IUSzWHSvy1xunHhx+a8AUlaHo+M81XkrZpwmmL+7xcIT3dgqYr50v9NKA9EsKpsk2iyiTkxRs="
  # pulumi-bot token for testing
  - secure: "seoAILOl9Uw3Gzio+j61ootcthhcXo823MWE1Ce+hFxjKTqZgU82sRHQaiGkKJSlWvR9tFGTAjT9xhUmnfhRxbjlYrbzJjmbJBY7xVxxsP3yjQe6+wPYpEYa3RTjvK509VGNHBZsHX9Qts3nsKxmc5di1WxM5+pf/UN30XG6uMfDnhncUETmX2n1XBkWOBN8t045LiLpNfE2CVTqr1H2hIx1LXh0sLPCEpMO5Tx6W+fzHcXrmpytIAJXxDlkR9bmluxPetM402KLAAZaZLrU11MLc3wX+OQydkJgDqK1C3KWL0jDpecik4asNFuOkWt2DpLnqbPSISnO6KvbGx254ZyUjX+wMYaRy2EgqmD+gK0Wl0CYhMyZVjvGF90iCk/7lVmtrcpFNMcHtw5n0q9c5VrQKWSvRJWGgljHocZRFDTabRlx0FX3A8oBXIckWLk60opte8+iajD55F51QcXjtXQWvNXGDyTOzHu8T8/kcUCaRjmoVWmLV3wwhYv74SdPd+a0MNtX8REbL4tlAWdBvDaGUnk7hwQcbSd6zxKM1ZvF6O57aJv0kl/5uIlVyzi1hLEehyoc75b5zaHj3zZ8RthqUI0PLr7snjmDxxRGChMAL5XgvsAbklb2/u7XYvkd3JFSzGJTvOL2lkWPHknW+v2OALWvaL9v1S8m/jkis6c="

